version: '3.9'

services:
    web:
        build:
            dockerfile: dev.Dockerfile
        command: yarn dev
        ports:
            - 4500:4500
        volumes:
            # save the node_modules in docker volume otherwise docker will overwrite node_modules while mounting ./ to /app
            - nextjs-v1:/app/node_modules
            - ./:/app

volumes:
    nextjs-v1:
